name: ssis
services:
  server:
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=<YourStrong@Passw0rd>
    ports:
      - 1433:1433
    container_name: sql1
    hostname: sql1
    image: mcr.microsoft.com/mssql/server:2022-latest
